import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

export const profileStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.background },
  glowOrbTop: {
    position: 'absolute',
    top: -100,
    right: -80,
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: theme.colors.primary,
    opacity: 0.08,
  },
  glowOrbBottom: {
    position: 'absolute',
    bottom: -120,
    left: -80,
    width: 280,
    height: 280,
    borderRadius: 999,
    backgroundColor: theme.colors.primary,
    opacity: 0.06,
  },
  scroll: { flex: 1 },
  content: { paddingHorizontal: 24, paddingTop: 58, paddingBottom: 56 },
  centered: { justifyContent: 'center', alignItems: 'center' },
  eyebrow: {
    fontSize: 10,
    color: theme.colors.subtext,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    fontWeight: '600',
    marginBottom: 8,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    color: theme.colors.text,
    letterSpacing: -0.5,
  },
  subtitle: { color: theme.colors.subtext, marginTop: 6, fontSize: 13 },
  headerDivider: {
    height: 1,
    backgroundColor: theme.colors.divider,
    marginTop: 16,
    marginBottom: 24,
  },
  loadingText: { color: theme.colors.subtext, marginTop: 12 },
  errorText: { color: theme.colors.error, textAlign: 'center', marginBottom: 16 },
  retryBtn: {
    backgroundColor: theme.colors.primary,
    padding: 16,
    borderRadius: theme.radius.md,
    alignItems: 'center',
    width: '100%',
    marginTop: 8,
  },
  retryBtnText: { color: theme.colors.text, fontWeight: '700', fontSize: 16 },
  logoutBtn: {
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.error,
    borderRadius: theme.radius.md,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  logoutBtnText: { color: theme.colors.error, fontWeight: '700', fontSize: 16 },
  spacer: { height: 40 },
  version: { textAlign: 'center', color: theme.colors.subtext, fontSize: 12, marginBottom: 16 },
});
